import { User } from "./adminUsers.interface";

export const mockUsers: User[] = [
  {
    id: 1,
    name: "Alice Silva",
    email: "alice@empresa.com",
    role: "SUPER_ADMIN",
    status: "active",
    isNew: true,
    isOnline: true,
    avatar: "AS",
    createdAt: "2024-02-15",
    lastLogin: "2 min atrás",
    location: "São Paulo, BR",
  },
  {
    id: 2,
    name: "Bruno Costa",
    email: "bruno@empresa.com",
    role: "ADMIN",
    status: "active",
    isNew: false,
    isOnline: false,
    avatar: "BC",
    createdAt: "2023-11-10",
    lastLogin: "2 dias atrás",
    location: "Rio de Janeiro, BR",
  },
  {
    id: 3,
    name: "Carla Souza",
    email: "carla@cliente.com",
    role: "USER",
    status: "suspended",
    isNew: false,
    isOnline: false,
    avatar: "CS",
    createdAt: "2024-01-05",
    lastLogin: "1 mês atrás",
    location: "Lisboa, PT",
  },
  {
    id: 4,
    name: "Daniel Oliveira",
    email: "daniel@cliente.com",
    role: "USER",
    status: "active",
    isNew: true,
    isOnline: true,
    avatar: "DO",
    createdAt: "2024-02-20",
    lastLogin: "Agora",
    location: "Curitiba, BR",
  },
];
