export const leagueTranslations: Record<string, string> = {
  // Ligas Principais
  "English Premier League": "Premier League Inglesa",
  "English League Championship": "Championship Inglês",
  "Scottish Premier League": "Premier League Escocesa",
  "German Bundesliga": "Bundesliga Alemã",
  "Italian Serie A": "Série A Italiana",
  "French Ligue 1": "Ligue 1 Francesa",
  "Spanish La Liga": "La Liga Espanhola",
  "Greek Superleague Greece": "Superliga Grega",
  "Dutch Eredivisie": "Eredivisie Holandesa",
  "Belgian Pro League": "Jupiler Pro League Belgica",
  "Turkish Super Lig": "Super Lig Turca",
  "Danish Superliga": "Superliga Dinamarquesa",
  "Portuguese Primeira Liga": "Primeira Liga Portuguesa",
  "American Major League Soccer": "MLS",
  "Swedish Allsvenskan": "Allsvenskan Sueca",
  "Mexican Primera League": "Liga MX",
  "Brazilian Serie A": "Brasileirão Série A",
  "Ukrainian Premier League": "Premier League Ucraniana",
  "Russian Football Premier League": "Premier League Russa",
  "Australian A-League": "A-League Australiana",
  "Norwegian Eliteserien": "Eliteserien Norueguesa",
  "Chinese Super League": "Superliga Chinesa",
  "_No League": "Sem Liga",

  // Segundas Divisões
  "Italian Serie B": "Série B Italiana",
  "Scottish Championship": "Campeonato Escocês",
  "English League 1": "League One Inglesa",
  "English League 2": "League Two Inglesa",
  "Italian Serie C Girone C": "Série C Italiana",
  "German 2. Bundesliga": "2. Bundesliga Alemã",
  "Spanish La Liga 2": "La Liga 2 Espanhola",
  "French Ligue 2": "Ligue 2 Francesa",
  "Swedish Superettan": "Superettan Sueca",
  "Brazilian Serie B": "Brasileirão Série B",
  "Argentinian Primera Division": "Primeira División Argentina",
  "Polish Ekstraklasa": "Ekstraklasa Polônia",

  // Copas e Competições Internacionais
  "FIFA World Cup": "Copa do Mundo FIFA",
  "Uruguayan Primera Division": "Primera División Uruguaia",
  "American NASL": "NASL - EUA",
  "Norwegian 1. Divisjon": "1. Divisjon Norueguesa",
  "Welsh Premier League": "Premier League Galesa",
  "UEFA Champions League": "UEFA Champions League",
  "UEFA Europa League": "UEFA Europa League",
  "FA Cup": "Copa da Inglaterra",
  "Copa del Rey": "Copa do Rei",
  "Coupe de France": "Copa da França",
  "DFB-Pokal": "Copa da Alemanha",
  "UEFA Nations League": "UEFA Nations League",
  "African Cup of Nations": "Copa das Nações Africanas",
  "Colombia Categoría Primera A": "Categoría Primeira A Colombiana",
  "Confederations Cup": "Copa das Confederações",
  "Copa America": "Copa América",
  "Copa Argentina": "Copa Argentina",
  "Copa Libertadores": "Copa Libertadores",
  "UEFA European Championships": "Campeonato Europeu",
  "FIFA Club World Cup": "Mundial de Clubes",
  "Coupe de la Ligue": "Copa da Liga Francesa",
  "International Champions Cup": "International Champions Cup",
  "Coppa Italia": "Copa da Itália",
  "Supercoppa Italiana": "Supercopa Italiana",
  "Taca de Liga": "Copa da Liga Portuguesa",
  "Taca de Portugal": "Copa de Portugal",
  "Supercopa de Espana": "Supercopa da Espanha",
  "UEFA Super Cup": "Supercopa da UEFA",
  "Venezuela Primera Division": "Primeira División Venezuelana",

  // Ligas Específicas
  "_Defunct Soccer Teams": "Times Extintos",
  "Moroccan Championship": "Campeonato Marroquino",
  "American NWSL": "NWSL",
  "European Cup": "Copa Europeia",
  "UEFA Cup": "Copa da UEFA",
  "Football League First Division": "Primeira Divisão Inglesa Histórica",
  "Football League Super Cup": "Supercopa Inglesa",
  "International Friendlies": "Amistosos Internacionais",
  "FIFA Womens World Cup": "Copa do Mundo Feminina",
  "UEFA European Under-21 Championship": "Euro Sub-21",
  "Club Friendlies": "Amistosos de Clubes",
  "EFL Cup": "Copa da Liga Inglesa",
  "FA Community Shield": "Supercopa da Inglaterra",
  "English National League": "National League Inglesa",
  "Argentinian Primera B Nacional": "Primeira B Nacional Argentina",
  "Albanian Superliga": "Superliga Albanesa",
  "Andorran 1a Divisió": "Primeira Divisão Andorrana",
  "Armenian Premier League": "Premier League Armênia",
  "Australia ACT NPL": "NPL ACT Australiana",
  "Austrian Bundesliga": "Bundesliga Austríaca",
  "Belarus Vyscha Liga": "Vyscha Liga Bielorrussa",
  "Belgian First Division B": "Primeira Divisão B Belga",
  "Bosnian Premier Liga": "Premier Liga Bósnia",
  "Brazilian Serie C": "Brasileirão Série C ",
  "Bulgarian First League": "Primeira Liga Búlgara",
  "Chile Primera Division": "Primeira División Chilena",
  "China League One": "China League One",
  "Croatian First Football League": "Primeira Liga Croata",
  "Cypriot First Division": "Primeira Divisão Cipriota",
  "Czech First League": "Primeira Liga Tcheca",
  "Danish 2nd Division": "Segunda Divisão Dinamarquesa",
  "Japanese J1 League": "J1 League Japonesa",
  "Estonian Meistriliiga": "Meistriliiga Estoniana",
  "Faroe Islands Premier League": "Premier League das Ilhas Faroé",
  "Finnish Veikkausliiga": "Veikkausliiga Finlandesa",
  "French Championnat National": "Championnat National Francês",
  "Georgian Erovnuli Liga": "Erovnuli Liga Georgiana",
  "Germany Liga 3": "3. Liga Alemã",
  "Greek Super League 2": "Super League 2 Grega",
  "Dutch Eerste Divisie": "Eerste Divisie Holandesa",
  "Icelandic Úrvalsdeild karla": "Úrvalsdeild Islandesa",
  "Irish Premier Division": "Premier Division Irlandesa",
  "Israeli Premier League": "Premier League Israelense",
  "Italy Serie D Girone D": "Série D Italiana",
  "English Northern Premier League Premier Division": "Northern Premier League Inglaterra",
  "English Isthmian League Premier Division": "Isthmian League Inglaterra",
  "English Southern Premier League South Division": "Southern Premier League Inglaterra",
  "Kazakhstan Premier League": "Premier League Cazaque",
  "Latvian Higher League": "Liga Letônia",
  "Lithuanian A Lyga": "A Lyga Lituana",
  "Macedonian First League": "Primeira Liga Macedônia",
  "Maltese Premier League": "Premier League Maltesa",
  "Mexican Liga de Expansión MX": "Liga de Expansión MX",
  "Moldovan National Division": "Divisão Nacional Moldava",
  "Montenegrin First League": "Primeira Liga Montenegrina",
  "Moroccan Botola 2": "Botola 2 Marroquina",
  "Northern Irish Premiership": "Premiership da Irlanda do Norte",
  "Polish I liga": "I Liga Polonesa",
  "Portuguese LigaPro": "LigaPro Portuguesa",
  "Qatar Stars League": "Liga do Qatar",
  "Romanian Liga II": "Liga II Romena",
  "Russian Football National League": "Liga Nacional Russa",
  "San-Marino Campionato": "Campeonato Sanmarinense",
  "Saudi-Arabian Pro League": "Liga Profissional Saudita",
  "Scottish League 1": "League One Escocesa",
  "Scottish League 2": "League Two Escocesa",
  "Serbian Super Liga": "Super Liga Sérvia",
  "Slovak First Football League": "Primeira Liga Eslovaca",
  "Primera División RFEF Group 1": "Primera RFEF Grupo 1",
  "Swedish Division 1 North": "Division 1 Norte Sueca",
  "Swiss Super League": "Super Liga Suíça",
  "Turkish 1 Lig": "1. Lig Turca",
  "Ukrainian First League": "Primeira Liga Ucraniana",
  "UAE Pro League": "Liga dos Emirados Árabes",
  "Turkish 2 Lig": "2. Lig Turca",
  "English National League North": "National League Norte",
  "English National League South": "National League Sul",
  "Danish 1st Division": "Primeira Divisão Dinamarquesa",
  "American USL Championship": "USL Championship",
  "Bolivian Primera División": "Primera División Boliviana",
  "Ecuadorian Serie A": "Série A Equatoriana",
  "Paraguayan Primera Division": "Primera División Paraguaia",
  "Peruvian Primera Division": "Primera División Peruana",
  "South Korean K League 1": "K League 1 Sul-Coreana",
  "Hungarian NB I": "NB I Húngara",
  "Romanian Liga I": "Liga I Romena",
  "Slovenian 1. SNL": "1. SNL Eslovena",
  "Azerbaijani Premier League": "Premier League Azerbaijana",
  "Luxembourg National Division": "Divisão Nacional Luxemburguesa",
  "German Regionalliga Nord": "Regionalliga Norte Alemã",
  "Swiss Challenge League": "Challenge League Suíça",
  "AFC Champions League Elite": "Liga dos Campeões da AFC",
  "CAF Champions League": "Liga dos Campeões da CAF",
  "CONCACAF Champions Cup": "Copa dos Campeões da CONCACAF",
  "Scottish FA Cup": "Copa da Escócia",
  "Copa Sudamericana": "Copa Sul-Americana",
  "Copa do Brasil": "Copa do Brasil",
  "CONCACAF Central American Cup": "Copa da América Central",
  "Iranian Azadegan League": "Liga Azadegan Iraniana",
  "Iranian Persian Gulf Pro League": "Liga do Golfo Pérsico Iraniana",
  "Thai Premier League": "Liga Tailandesa",
  "Thai League 2": "Liga 2 Tailandesa",
  "Kenyan Premier League": "Premier League Queniana",

  // Continuação com todas as ligas restantes...
  "German Regionalliga West": "Regionalliga Oeste Alemã",
  "German Regionalliga SudWest": "Regionalliga Sudoeste Alemã",
  "German Regionalliga Bayern": "Regionalliga Baviera Alemã",
  "German Regionalliga Nordost": "Regionalliga Nordeste Alemã",
  "Primera División RFEF Group 2": "Primera RFEF Grupo 2",
  "Spanish Segunda División B Group 3": "Segunda B Grupo 3 Espanhola",
  "Spanish Segunda División B Group 4": "Segunda B Grupo 4 Espanhola",
  "Algerian Ligue 1": "Ligue 1 Argelina",
  "Senegal Ligue 1": "Ligue 1 Senegalesa",
  "Northern Irish Championship": "Campeonato da Irlanda do Norte",
  "Svenska Cupen": "Copa Sueca",
  "Irish First Division": "First Division Irlandesa",

  // ... (adicionar todas as ligas restantes seguindo o mesmo padrão)

  // Ligas com nomes muito específicos mantêm o original com pequenas adaptações
  "Italy Serie D Girone B": "Série D Italiana Girone B",
  "Italy Serie D Girone C": "Série D Italiana Girone C",
  "Italy Serie D Girone E": "Série D Italiana Girone E",
  "Italy Serie D Girone F": "Série D Italiana Girone F",
  "Italy Serie D Girone G": "Série D Italiana Girone G",
  "Italy Serie D Girone H": "Série D Italiana Girone H",
  "Italy Serie D Girone I": "Série D Italiana Girone I",
  "Italy Serie D Girone A": "Série D Italiana Girone A",

  "FA Trophy": "FA Trophy",
  "Malaysian Premier League": "Liga Premier da Malásia",
  "Indonesian Super League": "Liga Super Indonésia",
  "Indian Super League": "Superliga Indiana",
  "Malaysian Super League": "Superliga da Malásia",
  "Cambodia C-League": "C-League Cambojana",
  "Uzbekistan Super League": "Superliga do Uzbequistão",
  "Singapore Premier League": "Premier League de Singapura",
  "Austrian Erste Liga": "Erste Liga Austríaca",
  "Indian I-League": "I-League Indiana",
  "South African Premier Soccer League": "Premier Soccer League Sul-Africana",
  "Vietnamese V.League 1": "V.League 1 Vietnamita",
  "AFC Champions League Two": "Liga dos Campeões da AFC 2",
  "Australian A-League Women": "A-League Feminina Australiana",
  "Nicaragua Primera Division": "Primera División Nicaraguense",

  // ... continuar com todas as demais ligas

  "_No League Soccer": "Futebol Sem Liga",
  "Swedish Division 1 South": "Division 1 Sul Sueca",
  "EFL Trophy": "EFL Trophy",
  "English Womens Super League": "Superliga Feminina Inglesa",
  "UEFA Womens Euro": "Euro Feminino",
  "AFC Asian Cup": "Copa da Ásia",
  "OFC Nations Cup": "Copa das Nações da OFC",
  "CONCACAF Gold Cup": "Copa Ouro da CONCACAF",

  // Adicione todas as ligas restantes seguindo o mesmo padrão
};

export const translateLeague = (league: string): string => {
  return leagueTranslations[league] || league;
};