export const sportTranslations: Record<string, string> = {
  Soccer: "Futebol",
  Motorsport: "Automobilismo",
  Fighting: "Artes Marciais",
  Baseball: "Beisebol",
  Basketball: "Basquete",
  "American Football": "Futebol Americano",
  "Ice Hockey": "Hóquei no Gelo",
  Golf: "Golfe",
  Rugby: "Rúgbi",
  Tennis: "Tênis",
  Cricket: "Críquete",
  Cycling: "Ciclismo",
  "Australian Football": "Futebol Australiano",
  ESports: "Esportes Eletrônicos",
  Volleyball: "Vôlei",
  Netball: "Netball",
  Handball: "Handebol",
  Snooker: "Sinuca",
  "Field Hockey": "Hóquei em Campo",
  Darts: "Dardos",
  Athletics: "Atletismo",
  Badminton: "Badminton",
  Climbing: "Escalada",
  Equestrian: "Hipismo",
  Gymnastics: "Ginástica",
  Shooting: "Tiro Esportivo",
  "Extreme Sports": "Esportes Radicais",
  "Table Tennis": "Tênis de Mesa",
  "Multi Sports": "Esportes Múltiplos",
  Watersports: "Esportes Aquáticos",
  Weightlifting: "Levantamento de Peso",
  Skiing: "Esqui",
  Skating: "Patinação",
  Wintersports: "Esportes de Inverno",
  Lacrosse: "Lacrosse",
  Gambling: "Apostas",
  Gaelic: "Esportes Gaélicos",
};

// Função auxiliar para traduzir
export const translateSport = (sport: string): string => {
  return sportTranslations[sport] || sport;
};
